### PR TITLE
Fix panic on user application errors

### LINKED ISSUE #1344: Panic on user application error during cross-application call
# Motivation

If a cross-application call fails with a custom error, an assertion fails in `linera_execution::ExecutionStateView::run_user_action`.

```

 thread 'tokio-runtime-worker' panicked at /mnt/git/linera-protocol/linera-execution/src/execution.rs:234:9:
 assertion `left == right` failed
   left: 2
  right: 1
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Probable cause

User application errors abort execution by returning an error. The error is propagated back through the call stack, which then doesn't pop the application stack in the `ExecutionRuntime`. The problem then is that the `ExecutionStateView` checks the error for a user application error and continues execution if it is. This is a temporary solution for the client not being able to skip receiving invalid messages.

# Proposed solution

For now, pop the call stack before propagating errors. Longer term, have the client support skipping invalid incoming messages and don't handle user application errors in a special manner.

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

It's currently possible to cause a `panic` inside validator shards by returning custom errors from applications. This happens because an assertion is triggered due to a bug introduced recently. The bug happens because the runtime application call stack is not updated when ignoring user errors.

## Proposal

Always update the application call stack before checking for errors.

## Test Plan

A unit test was added for the scenario where an application returns a custom user error. Execution should finish successfully.

## Release Plan

Nothing needed.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

Closes #1344

### CODE REVIEW

File: linera-execution/tests/test_execution.rs [hunk 1]
```diff
@@ -329,3 +346,63 @@ async fn test_simple_user_operation_with_leaking_session() -> anyhow::Result<()>
...
+        )
+        .await
+        .unwrap();
+    assert_eq!(
+        result,
+        vec![ExecutionResult::User(
+            app_id,
+            RawExecutionResult::default().with_authenticated_signer(Some(owner))
+        ),]
+    );
```
Comment (jvff) [inline linera-execution/tests/test_execution.rs:405]: I'm not sure about this. Should a failed execution contain anything in the result?

Comment (ma2bd) [reply linera-execution/tests/test_execution.rs:405]: `RawExecutionResult::default()` is empty anyway

File: linera-execution/src/execution.rs [hunk 2]
```diff
@@ -216,15 +216,27 @@ where
...
         // TODO(#989): Make user errors fail blocks again.
-        let mut result = if let Err(ExecutionError::UserError(message)) = &call_result {
-            tracing::error!("Ignoring error reported by user application: {message}");
-            RawExecutionResult::default()
-        } else {
-            call_result?
+        let mut result = match (runtime_result, call_result) {
+            (
+                Err(ExecutionError::UserError(message)),
+                Err(ExecutionError::MissingRuntimeResponse),
```
Comment (ma2bd) [inline linera-execution/src/execution.rs:226]: Do we need to check the `ExecutionError::MissingRuntimeResponse` ?

**Review by ma2bd — APPROVED** [review]
Thanks!

File: linera-execution/src/runtime.rs [hunk 3]
```diff
@@ -536,11 +536,12 @@ where
         let value_future = tokio::task::spawn_blocking(move || {
             code.handle_query(query_context, runtime_sender, argument)
         });
-        runtime_actor.run().await?;
```
Comment (ma2bd) [inline linera-execution/src/runtime.rs:539]: We could add `// TODO(#989): simplify after message failures are not ignored` or equivalent in all those places

Comment (jvff) [reply linera-execution/src/runtime.rs:539]: Good point. Done :tada:

File: linera-execution/src/execution.rs (hunk 2 above)
Comment (ma2bd) [reply linera-execution/src/execution.rs:226]: One could use `_` for the second element of the pair then. Optionally, it could also be `Err(error)` together with `assert!(matches(error, ExecutionError::MissingRuntimeResponse))`.
