### PR TITLE
Fix missing application registration messages

### LINKED ISSUE #1417: Investigate possible missing application registration messages
If the top-level application #1 calls application #2 and #2 sends a message, it looks like we're currently assuming that #1 sends messages to at least the same recipients as #2.

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

Messages sent by called applications were not preceded by system messages to register the application to receive the message on the destination chain. This meant that receiving the messages would fail unless the application was already registered or if a chain owner requests for the application manually.

## Proposal

Rewrite `update_execution_outcomes_with_app_registrations` to check for outgoing messages in all execution outcomes of the call stack. System messages are then created for all outgoing user application messages to their respective destination chains.

## Test Plan

Some unit tests were added to cover different scenarios of called applications sending messages.

## Release Plan

Nothing needed.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

Fixes #1417

### CODE REVIEW

File: linera-execution/src/execution.rs [hunk 1]
```diff
@@ -215,36 +216,65 @@ where
...
-                    applications: applications.clone(),
-                },
-            });
+        let user_application_outcomes = results.iter().filter_map(|outcome| match outcome {
+            ExecutionOutcome::User(application_id, result) => Some((application_id, result)),
+            _ => None,
+        });
+
+        let mut applications_to_register_per_destination =
+            HashMap::<&Destination, BTreeSet<UserApplicationId>>::new();
```
Comment (ma2bd) [inline linera-execution/src/execution.rs:233]: Would `HashMap::<_, BTreeSet<_>>` be enough?

File: linera-execution/src/execution.rs [hunk 2]
```diff
@@ -215,36 +216,65 @@ where
...
+            }
         }
-        if !system_outcome.messages.is_empty() {
-            results.insert(0, ExecutionOutcome::System(system_outcome));
+
+        if applications_to_register_per_destination.is_empty() {
+            return Ok(results);
         }
+
+        let registration_messages = applications_to_register_per_destination
```
Comment (ma2bd) [inline linera-execution/src/execution.rs:248]: nit: `let messages = ` is probably obvious enough?

File: linera-execution/tests/test_execution.rs [hunk 3]
```diff
@@ -429,6 +430,501 @@ async fn test_cross_application_error() -> anyhow::Result<()> {
...
+        ExecutionStateView::<MemoryContext<TestExecutionRuntimeContext>>::from_system_state(
+            state,
+            ExecutionRuntimeConfig::Synchronous,
+        )
+        .await;
+
+    let mut applications = register_mock_applications(&mut view, 2).await?;
+    let (caller_id, caller_application) = applications
+        .next()
+        .expect("Missing caller mock application");
```
Comment (ma2bd) [inline linera-execution/tests/test_execution.rs:533]: nit: Generally, we're trying to follow the pattern `.expect("something should be true")`

**Review by ma2bd — APPROVED** [review]
Thanks for the fix!

File: linera-execution/tests/test_execution.rs [hunk 4]
```diff
@@ -748,6 +748,183 @@ async fn test_message_from_session_call() -> anyhow::Result<()> {
...
+/// `destination_chain`.
+///
+/// The "caller" application is the entrypoint, starting by executing an operation. It will call
+/// a "silent_target" application which does not send any messages, and the "sending_target"
+/// application which will the send the two messages described above.
+///
+/// As a result of this scenario, the `first_destination_chain` should receive a message
+/// registering the "caller" and the "sending_target" applications, while the
+/// `second_destination_chain` should receive a message registering only the "sending_target"
+/// application. There should not be any messages registering the "silent_target" application.
```
[the remark this answers is not in the document]
Comment (jvff) [reply linera-execution/tests/test_execution.rs]: Done.

File: linera-execution/src/execution.rs (hunk 2 above)
Comment (jvff) [reply linera-execution/src/execution.rs]: Done.

File: linera-execution/tests/test_execution.rs (hunk 3 above)
Comment (jvff) [reply linera-execution/tests/test_execution.rs]: Done.
