### PR TITLE
Test publish

### LINKED ISSUE #802: fix test for docsrs
https://github.com/linera-io/linera-protocol/actions/runs/5173690463/jobs/9319195346

```
Error: Building documentation failed

Caused by:
    Building documentation failed

Caused by:
    failed to load local package /home/runner/work/_temp/crates/linera-core/package/linera-core-0.1.0

Caused by:
    command failed: exit status: 101

Stack backtrace:
   0: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:2065:27
   1: docs_rs::utils::cargo_metadata::CargoMetadata::load_from_rustwide
             at ./src/utils/cargo_metadata.rs:18:19
   2: docs_rs::docbuilder::rustwide_builder::RustwideBuilder::build_local_package
             at ./src/docbuilder/rustwide_builder.rs:316:24
   3: cratesfyi::BuildSubcommand::handle_args
             at ./src/bin/cratesfyi.rs:418:21
   4: cratesfyi::CommandLine::handle_args
             at ./src/bin/cratesfyi.rs:161:18
   5: cratesfyi::main
             at ./src/bin/cratesfyi.rs:65:23
   6: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:134:18
   8: std::rt::lang_start::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:166:18
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  10: std::rt::lang_start
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:165:17
  11: main
  12: <unknown>
  13: __libc_start_main
  14: _start

Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by ma2bd**
## Motivation

* Eventually fix PR #802
* Test crate publishing

## Proposal

* Create a package list `packages.txt`
* Create `scripts/test_publish.sh` using a combination of `cargo index` and `cargo-local-registry`
* Create `scripts/publish.sh`

CAVEAT: `cargo index` uses `Cargo.lock` so it must be accurate.

## Test Plan

```
scripts/test_publish packages.txt ~/tmp_registry
```

### CODE REVIEW

**Review by jvff — APPROVED** [review]

File: scripts/test_publish.sh [hunk 1]
```diff
@@ -0,0 +1,40 @@
+#!/bin/bash
+
+set -x -e
+
+# Usage:
+#   cargo install cargo-local-registry
+#   cargo install cargo-index
+#   grep -v '^#' packages.txt | scripts/test_publish.sh REGISTRY
```
Comment (MathieuDutSik) [inline scripts/test_publish.sh:8]: * The documentation should indicate what is being tested. I think it is the way that the packages are ordered. But I am not entirely sure, so this deserves mentioning.
* I find the check for the nothing uncommited in git to be just annoying. If you edit your system, you want to do that check at the end.
* Also, important is whether the testing is needed before doing the `publish.sh`. A priori no, but better said than nothing.
* The command modifies the `.cargo/config.toml`. Why so? The construction of the REGISTRY, the git action and so on make it looks than much more than just testing is done.

File: scripts/publish.sh [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#!/bin/bash
+
+set -x -e
+
+# Usage: grep -v '^#' packages.txt | scripts/publish.sh
+
+# Publish the given packages.
+while read LINE; do
+    cargo publish -p $LINE
+done
```
Comment (MathieuDutSik) [inline scripts/publish.sh:10]: It would be nice to do the following:
* Add the documentation for what are the requirements to the packages. I think the dependencies need to be ordered. Also, the individual requirements of packages from https://doc.rust-lang.org/cargo/reference/publishing.html have to be satisfied. Anything else?
* Write that if unsure things can be tested.

[the remark this answers is not in the document]
Comment (ma2bd) [reply scripts/publish.sh]: done

Comment (ma2bd) [reply scripts/publish.sh]: `packages.txt` is already self-documented

File: scripts/test_publish.sh (hunk 1 above)
Comment (ma2bd) [reply scripts/test_publish.sh]: > I find the check for the nothing uncommited in git to be just annoying.

I narrowed down the check to a single file.

> The command modifies the .cargo/config.toml.

It's temporary

File: packages.txt [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+linera-execution
+linera-chain
+linera-storage-service
+linera-storage
+linera-core
+linera-sdk-derive
+linera-sdk
+linera-rpc
+linera-service
+linera-service-graphql-client
```
[the remark this answers is not in the document]
Comment (ma2bd) [reply packages.txt:20]: Yes it is, actually

[the remark this answers is not in the document]
Comment (ma2bd) [reply packages.txt:20]: Fixed!
