### PR TITLE
Wait for refund messages before final assertions in Matching Engine end-to-end test

### LINKED ISSUE #1854: test_wasm_end_to_end_matching_engine::service_grpc is flaky
Seen failing on the main branch:
```
thread 'test_wasm_end_to_end_matching_engine::service_grpc' panicked at linera-service/tests/end_to_end_tests.rs:59:13:
assertion `left == right` failed
  left: Amount(1000000000000000000)
 right: Amount(4000000000000000000)
```
https://github.com/linera-io/linera-protocol/actions/runs/8483991057/job/23246115005

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

The Matching Engine end-to-end test would sometimes fail in CI. This was caused by a race condition in the test, where some queries to node services to obtain token balances for the final assertions raced the notifications to the node services about the blocks that send the final tokens.

## Proposal

Wait until the node services receive the blocks that send the messages, so that they can execute them and receive the remaining tokens.

## Test Plan

I managed to increase the frequency of the race condition significantly by adding a delay when proxying the notification to the node service, just before the following line:

https://github.com/linera-io/linera-protocol/blob/538ce38b3f9a1c41c9dcd4a957f959b66fa2b5cf/linera-service/src/grpc_proxy.rs#L398

After the fix, I could not reproduce the error.

## Release Plan

Nothing needed.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)
- Fixes #1854
- Future work:
  - #1874 
  - #1888

### CODE REVIEW

File: linera-service/tests/end_to_end_tests.rs [hunk 1]
```diff
@@ -1399,10 +1419,42 @@ async fn test_wasm_end_to_end_matching_engine(config: impl LineraNetConfig) {
...
+    .expect("Missing notification of canceled order refunds to chain A")
+    .expect("Failed to wait for order refund messages");
+
+    tokio::time::timeout(
+        Duration::from_secs(5),
+        node_service_b.wait_for_messages(chain_b, chain_b_refund_admin_tip),
+    )
+    .await
+    .expect("Missing notification of canceled order refunds to chain B")
+    .expect("Failed to wait for order refund messages");
```
[the remark this answers is not in the document]
Comment (ma2bd) [reply linera-service/tests/end_to_end_tests.rs:1457]: OK I kinda agree with @MathieuDutSik that this code is a little verbose. Also, why do we need a timeout around `wait_for_message`?

File: linera-service/src/cli_wrappers/wallet.rs [hunk 2]
```diff
@@ -1011,6 +1033,57 @@ impl NodeService {
...
+        let query = format!(
+            r#"query {{
+                block(hash: "{certificate_hash}", chainId: "{receiver_chain}") {{ hash }}
+            }}"#
+        );
+        let retry_delays = iter::repeat(Duration::from_millis(100))
+            .take(10)
+            .chain(iter::repeat(Duration::from_secs(1)));
+
+        let data = self.query_node_with_retries(query, retry_delays).await?;
```
Comment (ma2bd) [inline linera-service/src/cli_wrappers/wallet.rs:1078]: Why not use the same retry policy here as everywhere else?

File: linera-service/tests/end_to_end_tests.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (jvff) [reply linera-service/tests/end_to_end_tests.rs]: Removed the test time optimizations, so it should be cleaner now.

File: linera-service/src/cli_wrappers/wallet.rs (hunk 2 above)
Comment (jvff) [reply linera-service/src/cli_wrappers/wallet.rs]: The goal was to avoid waiting a whole second before retrying, because the race condition was likely in the order of milliseconds. But we can optimize this later, so I removed it :+1:

**Review by ma2bd — APPROVED** [review]
Thanks @jvff for debugging and fixing this annoying issue!

File: linera-service/src/cli_wrappers/wallet.rs [hunk 3]
```diff
@@ -1028,6 +1029,54 @@ impl NodeService {
...
+    ///
+    /// In practice, the `receiver_chain` is only used by the node service to access the storage.
+    pub async fn wait_for_messages(
+        &self,
+        receiver_chain: ChainId,
+        certificate_hash: CryptoHash,
+    ) -> Result<()> {
+        let query = format!(
+            r#"query {{
+                block(hash: "{certificate_hash}", chainId: "{receiver_chain}") {{ hash }}
```
Comment (afck) [inline linera-service/src/cli_wrappers/wallet.rs:1067]: (Turns out the `receiver_chain` is pretty much being ignored here: The node service could use _any_ of its `ChainClient`s, since they all share the same storage. Not an ideal API; but not the fault of this PR, of course!)

**Review by afck — APPROVED** [review]
