### PR TITLE
Tracing improvements

### LINKED ISSUE #3499: `ChainWorkerRequests` execute in the wrong tracing context
They execute in the context of the call that spawned the actor task, not the call that made the request.  We should attach a tracing context to each request and enter it for execution.

### PR DESCRIPTION
**Pull request by Twey**
## Motivation
https://github.com/linera-io/linera-protocol/issues/3499

## Proposal
Pass a span with each request.

## Test Plan
CI.

## Release Plan
- Nothing to do / These changes follow the usual release cycle.

## Links
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)
- Fixes #3499.

### CODE REVIEW

File: linera-core/src/worker.rs [hunk 1]
```diff
@@ -811,7 +815,7 @@ where
     }
 
     /// Processes a confirmed block certificate.
-    #[instrument(skip_all, fields(
+    #[instrument(skip_all,  fields(
```
Comment (ma2bd) [inline linera-core/src/worker.rs:818]: typo

File: linera-core/src/chain_worker/state/mod.rs [hunk 2]
```diff
@@ -204,6 +204,7 @@ where
         &mut self,
         proposal: BlockProposal,
     ) -> Result<(ChainInfoResponse, NetworkActions), WorkerError> {
+        tracing::debug!("handling block proposal: {proposal:#?}");
```
Comment (ma2bd) [inline linera-core/src/chain_worker/state/mod.rs:207]: leftover? We could certainly add TRACE-level log for all handlers.

**Review by ma2bd — COMMENTED** [review]
LGTM but maybe @afck and @jvff wnat to weigh in

File: linera-core/src/chain_worker/actor.rs [hunk 3]
```diff
@@ -285,18 +288,21 @@ where
...
-        while let Some(request) = incoming_requests.recv().await {
+        while let Some((request, span)) = incoming_requests.recv().await {
             // TODO(#2237): Spawn concurrent tasks for read-only operations
             trace!("Handling `ChainWorkerRequest`: {request:?}");
 
             let responded = match request {
                 #[cfg(with_testing)]
                 ChainWorkerRequest::ReadCertificate { height, callback } => callback
-                    .send(self.worker.read_certificate(height).await)
+                    .send(self.worker.read_certificate(height).instrument(span).await)
```
Comment (afck) [inline linera-core/src/chain_worker/actor.rs:305]: Should we deduplicate all the `instrument(span)`s (and also prevent that we forget adding it to calls in the future) by calling `handle_requests(…).instrument(span)` from `handle_requests_with_span`?

File: linera-core/src/chain_worker/state/mod.rs (hunk 2 above)
Comment (Twey) [reply linera-core/src/chain_worker/state/mod.rs:207]: I think this should be done with `tracing::instrument` though.

File: linera-core/src/worker.rs (hunk 1 above)
Comment (Twey) [reply linera-core/src/worker.rs:818]: Oh I was hoping `cargo fmt` would fix this one for me :sweat_smile:

File: linera-core/src/chain_worker/actor.rs (hunk 3 above)
Comment (Twey) [reply linera-core/src/chain_worker/actor.rs:305]: I was on the fence about doing this anyway :sweat_smile:

**Review by afck — APPROVED** [review]
