### PR TITLE
Thread pool

### LINKED ISSUE #3651: OOM on Web due to ephemeral threads
Currently the way we implement threads in Wasm means that every new thread grows the single shared Wasm memory.  Since Wasm provides no way to shrink the memory, this results in the memory usage growing with every new thread (i.e. every block executed) until it hits a browser-imposed limit and crashes.

Some solutions to this problem that I think should work, in ascending order of difficulty:
- change `linera-protocol` to use a fixed-size pool of threads that are re-used when executing bytecode
- change `wasm-bindgen` to use multiple memories, so that the thread's memory can be added to a fresh memory that is freed when the thread ends
- change our fork of `wasm-thread` to track a thread's used memory and release it when the thread exits

### PR DESCRIPTION
**Pull request by Twey**
## Motivation

https://github.com/linera-io/linera-protocol/issues/3651

## Proposal

Introduce a thread pool on top of `web-thread` and reüse a fixed pool of threads (here hardcoded to 20, without any particular rationale; we should make it configurable as future work).

## Test Plan

CI.  The pool logic is shared between the native and Web cases, so should be adequately tested by our usual end-to-end tests.

## Release Plan

- These changes should be backported to the latest `testnet` branch, then
    - be released in a new SDK,

## Links

- fixes #3651
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

### CODE REVIEW

File: linera-core/src/environment/mod.rs [hunk 1]
```diff
@@ -20,9 +22,7 @@ pub trait Environment: AutoTraits {
     type ValidatorNode: crate::node::ValidatorNode + AutoTraits + Clone;
     // TODO(#5064): we shouldn't hard-code `Send` + `Sync` here
```
Comment (ma2bd) [inline linera-core/src/environment/mod.rs:23]: Seems like you solved this TODO?

Comment (Twey) [reply linera-core/src/environment/mod.rs:23]: I did but saw this too late :sweat_smile: Removed in #5116.

File: linera-storage/src/db_storage.rs [hunk 2]
```diff
@@ -1081,6 +1087,9 @@ impl<Database, C> DbStorage<Database, C> {
         Self {
             database: Arc::new(database),
             clock,
+            // The `Arc` here is required on native but useless on the Web.
+            #[cfg_attr(web, expect(clippy::arc_with_non_send_sync))]
+            thread_pool: Arc::new(linera_execution::ThreadPool::new(20)),
```
Comment (ndr-ds) [inline linera-storage/src/db_storage.rs:1092]: Just curious: what's the rationale behind the 20 here?
