### PR TITLE
Fix syncing after `follow-chain` for child chains.

### LINKED ISSUE #3891: `follow-chain` does not work with child chains. (Testnet Babbage)
The backport of https://github.com/linera-io/linera-protocol/pull/3887 fails on `testnet_babbage`.

The main problem seems to be that we try to use "local" validators (i.e. the ones in the to-be-synchronized chain's state) in several places, and these are not defined for the uninitialized chain yet.

### PR DESCRIPTION
**Pull request by afck**
## Motivation

`sync` after `follow-chain` doesn't work.

## Proposal

Add a test (backport of https://github.com/linera-io/linera-protocol/pull/3887). Handle the case where a chain is uninitialized.

## Test Plan

The test was backported.

## Release Plan

- These changes should be released in a new SDK.

## Links

- Closes #3891.
- Test for `main` (doesn't have the bug): https://github.com/linera-io/linera-protocol/pull/3887
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

### CODE REVIEW

File: linera-core/src/client/mod.rs [hunk 1]
```diff
@@ -922,9 +922,7 @@ where
             .await?
             .info;
         let epoch = info.epoch;
-        let committees = info
-            .requested_committees
-            .ok_or(LocalNodeError::InvalidChainInfoResponse)?;
+        let committees = info.requested_committees.unwrap_or_else(BTreeMap::new);
```
Comment (deuszx) [inline linera-core/src/client/mod.rs:925]: I'm not sure I agree this is a good change. I understand it's necessary for the fix but:
- it's not possible for the protocol to execute correctly with empty committee
- if we requested it then it shouldn't be empty.

Comment (deuszx) [reply linera-core/src/client/mod.rs:925]: On the call-site we only pattern match on the first element of the tuple and interpret the `None` as a chain not-active. Maybe we can return `Ok(None)` entirely.

File: linera-core/src/client/mod.rs [hunk 2]
```diff
@@ -1750,9 +1750,12 @@ where
         #[cfg(with_metrics)]
         let _latency = metrics::SYNCHRONIZE_CHAIN_STATE_LATENCY.measure_latency();
 
-        let (epoch, mut committees) = self.epoch_and_committees(chain_id).await?;
+        let (epoch, mut committees) = match self.epoch_and_committees(chain_id).await? {
+            (Some(epoch), committees) => (epoch, committees),
+            (None, _) => self.known_committees().await?, // Chain is not active yet.
```
Comment (deuszx) [inline linera-core/src/client/mod.rs:1755]: This is a bit confusing for a number of reasons:
- both `epoch_and_committees` and `known_committees` return the same types
- `known_commitees` calls `epoch_commitees(chain_id)` as well

IIUC, in the case of "chain not active yet" we want to fetch the known committee from the admin chain, is that right?

Comment (afck) [reply linera-core/src/client/mod.rs:1755]: Yes. TBH I'm not sure what the "right committee" is in all those cases where we just need _nodes_ to synchronize from, as opposed to actual validators to ask to sign something. But maybe that's beyond the scope of this PR, and something we should just fix on `main` instead?

File: linera-core/src/client/mod.rs (hunk 1 above)
Comment (afck) [reply linera-core/src/client/mod.rs:925]: This also triggers a bunch of other changes, and I was trying to keep this PR small.

I'll look into cleaning up all those committee getters a bit; if it's not too big I'll add it to this PR.

File: linera-core/src/client/mod.rs (hunk 2 above)
Comment (deuszx) [reply linera-core/src/client/mod.rs:1755]: OK, agreed. BUT an empty committee can't be a right committee ever, right?

**Review by deuszx — DISMISSED** [review]
As discussed - approving this PR in the interest of keeping the backport minimal and fixing it on the `main` instead.

File: linera-core/src/client/mod.rs (hunk 2 above)
Comment (afck) [reply linera-core/src/client/mod.rs:1755]: That's true, yes.

**Comment by afck** [comment]
Closing this for now, since the fix breaks another test. I created https://github.com/linera-io/linera-protocol/issues/3891.
