### PR TITLE
Step 4 of clippy corrections

### LINKED ISSUE #5573: Enable clippy lints for bugs, perf issues, and API problems
## Enable clippy lints that catch bugs, perf issues, and API problems

These lints catch real issues — potential panics, unnecessary allocations, misleading APIs — but have existing violations that need cleanup first.

### Lints

| Lint | Violations | What it catches |
|------|----------:|----------------|
| `match_on_vec_items` | 1 | Vec indexing in match without bounds check (potential panic) |
| `iter_not_returning_iterator` | 2 | Method named `iter` that doesn't return `Iterator` (API contract violation) |
| `checked_conversions` | 4 | Manual bounds checks that should use `try_from` |
| `needless_collect` | 5 | `.collect::<Vec<_>>()` immediately re-iterated (unnecessary allocation) |
| `unnecessary_wraps` | 6 | Functions that always return `Ok(x)` or `Some(x)` (pointless wrapping) |
| `inefficient_to_string` | 10 | `.to_string()` on `&str` going through Display trait instead of `.to_owned()` |
| `used_underscore_binding` | 13 | `_x` bindings that are actually used (misleading "unused" convention) |
| `from_iter_instead_of_collect` | 24 | `FromIterator::from_iter(x)` instead of idiomatic `.collect()` |
| `or_fun_call` | 26 | `.unwrap_or(String::new())` allocating on the happy path instead of `.unwrap_or_default()` |
| `needless_pass_by_ref_mut` | 61 | `&mut` params that are never mutated (API lies about mutation) |
| `needless_pass_by_value` | 89 | By-value params that are only borrowed (unnecessary cloning at call sites) |

**Total: ~241 violations**

### Why

- `match_on_vec_items`, `checked_conversions`: correctness — prevent panics and incorrect bounds checks
- `needless_collect`, `or_fun_call`, `inefficient_to_string`, `needless_pass_by_value`: performance — avoid unnecessary allocations and copies
- `needless_pass_by_ref_mut`, `unnecessary_wraps`, `iter_not_returning_iterator`: API honesty — signatures should reflect actual behavior
- `used_underscore_binding`, `from_iter_instead_of_collect`: clarity — prevent misleading code patterns

### Work

1. Enable all lints as `warn` in Cargo.toml
2. Fix violations incrementally — most are mechanical and can be fixed with `cargo clippy --fix`. `needless_pass_by_value` and `needless_pass_by_ref_mut` need manual review since they change function signatures. Can be split across 2-3 PRs.
3. Once all violations are resolved and the lints have proven valuable, promote to `deny`

### PR DESCRIPTION
**Pull request by MathieuDutSik**
## Motivation

More clippy corrections that should be catch are added to `Cargo.toml`.

Fixes #5573 

## Proposal

Do it in a very straightforward way.

## Test Plan

CI

## Release Plan

We could be added to `testnet_conway`.

## Links

None

### CODE REVIEW

File: linera-views/src/views/queue_view.rs [hunk 1]
```diff
@@ -464,6 +464,7 @@ where
     /// assert_eq!(queue.elements().await.unwrap(), vec![42]);
     /// # })
     /// ```
+    #[allow(clippy::iter_not_returning_iterator)]
```
Comment (afck) [inline linera-views/src/views/queue_view.rs]: Should it be `try_iter_mut` then?

File: linera-views/src/backends/rocks_db.rs [hunk 2]
```diff
@@ -715,15 +715,16 @@ pub struct PathWithGuard {
     pub path_buf: PathBuf,
     /// The guard for the directory if one is needed
     #[serde(skip)]
-    _dir: Option<Arc<TempDir>>,
+    #[allow(dead_code)]
```
Comment (afck) [inline linera-views/src/backends/rocks_db.rs]: So on the one hand it _is_ dead code, but on the other hand it would trigger the `used_underscore_binding` lint? 🤨

File: linera-service/src/storage.rs [hunk 3]
```diff
@@ -445,6 +445,7 @@ example service:tcp:127.0.0.1:7878:table_do_my_test"
 }
 
 impl StorageConfig {
+    #[allow(clippy::used_underscore_binding)]
     pub fn maybe_append_shard_path(&mut self, _shard: usize) -> std::io::Result<()> {
         match &mut self.inner_storage_config {
             #[cfg(all(feature = "rocksdb", feature = "scylladb"))]
```
Comment (afck) [inline linera-service/src/storage.rs:451]: Maybe at this point it's clearer to just have two `fn maybe_append_shard_path`s: One with RocksDB/ScyllaDB and one without. The latter would then still have `_shard` with underscore and without `allow`.

File: linera-execution/src/wasm/runtime_api.rs [hunk 4]
```diff
@@ -842,7 +842,8 @@ where
     ///
     /// This is called by the metering instrumentation, but the fuel consumed argument is
     /// ignored.
-    fn check_execution_time(caller: &mut Caller, _fuel_consumed: u64) -> Result<(), RuntimeError> {
+    fn check_execution_time(caller: &mut Caller, fuel_consumed: u64) -> Result<(), RuntimeError> {
+        let _ = fuel_consumed;
```
Comment (afck) [inline linera-execution/src/wasm/runtime_api.rs]: We're trying to avoid `let _ =` in general, too.

File: linera-views/src/backends/rocks_db.rs (hunk 2 above)
Comment (MathieuDutSik) [reply linera-views/src/backends/rocks_db.rs]: Yes, that is the problem.

But there is a solution. Writing `_dir_guard: dir_guard`.

File: linera-service/src/storage.rs (hunk 3 above)
Comment (MathieuDutSik) [reply linera-service/src/storage.rs:451]: I think we have to choose a poison. And here the one I would prefer is the `#[allow(_)]` statement.

File: linera-execution/src/wasm/runtime_api.rs (hunk 4 above)
Comment (MathieuDutSik) [reply linera-execution/src/wasm/runtime_api.rs]: Here the poison I would choose is the allow and yes remove the `let _ = ....`.

File: linera-service/src/cli/net_up_utils.rs [hunk 5]
```diff
@@ -34,7 +34,8 @@ struct StorageConfigProvider {
     /// The storage config.
     config: StorageConfig,
     #[cfg(feature = "storage-service")]
-    _service_guard: Option<StorageServiceGuard>,
+    #[allow(dead_code)]
+    service_guard: Option<StorageServiceGuard>,
```
Comment (afck) [inline linera-service/src/cli/net_up_utils.rs]: So why does it complain about the underscore here?

Comment (MathieuDutSik) [reply linera-service/src/cli/net_up_utils.rs]: It is the same pattern as for the `dir_guard`.

File: linera-views/src/views/queue_view.rs (hunk 1 above)
Comment (MathieuDutSik) [reply linera-views/src/views/queue_view.rs]: Yes, that works.
