### PR TITLE
Fix the LRU caching bug - alternative solution

### LINKED ISSUE #4299: LRU cache out of sync with storage.
The modified benchmark in #4269 is failing with `message not received yet` errors. To reproduce:
* Check out https://github.com/linera-io/linera-protocol/commit/bbfe1354791e1ffe196b6c01602e91bb5b564df1.
* Start a local network with `cargo build -p linera-storage-service -p linera-service && cargo run --bin linera -- net up --validators 1 --shards 1 --with-faucet`
* Run multi-benchmark with: `RUST_BACKTRACE=1 cargo run --bin linera --features benchmark -- multi-benchmark --processes 2 --faucet http://localhost:8080/ --bps 2 --transactions-per-block 100 --num-chains 2 --close-chains --cross-wallet-transfers`

My [debug-not-received](https://github.com/afck/linera-protocol/tree/debug-not-received) branch contains a few added fixes, `main` merges, logs and, crucially, assertions that the LRU cache agrees with storage. On this branch we actually see those assertions fail.

### PR DESCRIPTION
**Pull request by bart-linera**
## Motivation

We could be dropping incoming messages in some cases due to how different kinds of caching in our system interact with one another.

## Proposal

Remove the context from cached ExecutionStateViews and restore it upon restoring from cache. This way the storage caches aren't saved, and the correct cache is used by all the views even when restored from execution state cache.

## Test Plan

Tested manually that it fixes the issue + CI for regressions

## Release Plan

- Nothing to do / These changes follow the usual release cycle.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)
- Alternative to #4303 
- Closes #4299

### CODE REVIEW

File: linera-views/src/store.rs [hunk 1]
```diff
@@ -255,3 +255,91 @@ pub trait TestKeyValueDatabase: KeyValueDatabase {
...
+
+    impl KeyValueStoreError for DummyStoreError {
+        const BACKEND: &'static str = "dummy";
+    }
+
+    impl WithError for DummyStore {
+        type Error = DummyStoreError;
+    }
+
+    impl ReadableKeyValueStore for DummyStore {
```
Comment (deuszx) [inline linera-views/src/store.rs]: Would it be correct to `panic!` here? to detect calls to something that shouldn't be called? Or maybe even use the `!` (unreachable) type?

Comment (bart-linera) [reply linera-views/src/store.rs]: Probably, as we don't expect these functions to actually be called. I'll try it out :+1:

File: linera-execution/src/system.rs [hunk 2]
```diff
@@ -93,6 +93,27 @@ pub struct SystemExecutionStateView<C> {
     pub event_subscriptions: MapView<C, (ChainId, StreamId), EventSubscriptions>,
 }
 
+impl<C: Context, C2: Context> ReplaceContext<C2> for SystemExecutionStateView<C> {
```
Comment (afck) [inline linera-execution/src/system.rs:97]: We should probably provide a `derive` macro for this at some point. (Not in this PR, of course.)

File: linera-core/src/chain_worker/state/temporary_changes.rs [hunk 3]
```diff
@@ -334,7 +337,12 @@ where
             .await?;
         self.0.execution_state_cache.insert_owned(
             &outcome.state_hash,
-            self.0.chain.execution_state.clone_unchecked()?,
+            self.0
+                .chain
+                .execution_state
+                .clone_unchecked()?
```
Comment (afck) [inline linera-core/src/chain_worker/state/temporary_changes.rs]: Is this necessary? Doesn't `with_context` clone everything anyway?

(Maybe it shouldn't, and take `self` instead? Or should it be called `clone_with_context`?)

Comment (bart-linera) [reply linera-core/src/chain_worker/state/temporary_changes.rs]: Ah, right - I initially removed it, but restored it after getting some test failures. It wasn't the reason, though, so it can be removed :+1:

(As for taking `self`, I tried that, but there is a view for which it is impossible to implement with taking ownership because of some `Arc`s in the structure.)

File: linera-execution/src/system.rs (hunk 2 above)
Comment (bart-linera) [reply linera-execution/src/system.rs:97]: It's problematic, because it's not straightforward how the `Result` type should be automatically defined. But if possible, then it should definitely be desirable :+1:

File: linera-views/src/views/mod.rs [hunk 4]
```diff
@@ -96,6 +96,15 @@ pub trait View: Sized {
     }
 }
 
+/// A view which can have its context replaced.
+pub trait ReplaceContext<C: crate::context::Context>: View {
+    /// The type returned after replacing the context.
+    type Result: View<Context = C>;
```
Comment (ma2bd) [inline linera-views/src/views/mod.rs]: nit: `Result` is a bit overloaded. I believe `Target` is idiomatic

File: linera-execution/src/system.rs (hunk 2 above)
Comment (ma2bd) [reply linera-execution/src/system.rs:97]: IIRC the current macro is already introspecting the container declaration to detect the context parameter.

File: linera-views/src/views/mod.rs [hunk 5]
```diff
@@ -96,6 +96,15 @@ pub trait View: Sized {
...
+
+    /// Returns a view with a replaced context.
+    async fn with_context(&self, ctx: impl FnOnce(&Self::Context) -> C + Clone) -> Self::Result;
```
Comment (ma2bd) [inline linera-views/src/views/mod.rs]: What's the reasoning behind using a clonable `FnOnce` function? Why not `Fn`?

Comment (ma2bd) [reply linera-views/src/views/mod.rs]: Also we may want to consume `self` to simplify the code (even if this means calling `clone_unchecked` first).

`clone_unchecked` takes `&mut self` by the way. Maybe something to double-check because there could be a reason (EDIT: actually there is! I just remembered)

Comment (bart-linera) [reply linera-views/src/views/mod.rs]: The reasoning was that we don't call this more than once, but we sometimes need to pass it to multiple calls of `with_context` on child views, so we need to clone it.

As for consuming self, as far as I can tell, it's impossible to implement it this way on `ReentrantByteCollectionView` due to the `Arc<RwLock>`s inside it - even if we own the `Arc`s, it doesn't guarantee exclusive ownership of whatever is inside, and there might be a non-cloneable view inside on which we need to call `with_context` as well.

File: linera-execution/src/system.rs (hunk 2 above)
Comment (bart-linera) [reply linera-execution/src/system.rs:97]: Ah, I see, it just seems to assume that context is the first generic parameter. If we make that assumption anyway, then maybe it wouldn't be that hard to implement the macro after all :thinking:

Comment (deuszx) [reply linera-execution/src/system.rs:97]: We should watch out for these assumptions in macro.

File: linera-views/src/views/mod.rs (hunk 5 above)
Comment (ma2bd) [reply linera-views/src/views/mod.rs]: Then we probably want to take `&mut self` because saving the cloned view later can modify the storage. (And &-references on views are not allowed to mutate the DB)

Comment (ma2bd) [reply linera-views/src/views/mod.rs:105]: (And &-references on views are not allowed to mutate the DB)

File: linera-execution/src/system.rs (hunk 2 above)
Comment (ma2bd) [reply linera-execution/src/system.rs:97]: We do!

File: linera-views/src/store.rs [hunk 6]
```diff
@@ -255,3 +255,91 @@ pub trait TestKeyValueDatabase: KeyValueDatabase {
         database.open_shared(&[])
     }
 }
+
+/// A module containing a dummy store used for caching views.
+pub mod inactive_store {
+    use super::*;
+
+    /// A store which is not actually stored anything - used for caching views.
```
Comment (afck) [inline linera-views/src/store.rs]:
```suggestion
    /// A store which does not actually store anything - used for caching views.
```

**Review by afck — APPROVED** [review]

**Review by afck — APPROVED** [review]

File: linera-views/src/views/mod.rs [hunk 7]
```diff
@@ -96,6 +96,16 @@ pub trait View: Sized {
     }
 }
 
+/// A view which can have its context replaced.
+pub trait ReplaceContext<C: crate::context::Context>: View {
```
Comment (Twey) [inline linera-views/src/views/mod.rs:100]: I'm not sure I understand the reason for this parameter.  It's anyway fixed by `Target`.

File: linera-views/src/views/mod.rs [hunk 8]
```diff
@@ -96,6 +96,16 @@ pub trait View: Sized {
...
+    /// The type returned after replacing the context.
+    type Target: View<Context = C>;
+
+    /// Returns a view with a replaced context.
+    async fn with_context(&mut self, ctx: impl FnOnce(&Self::Context) -> C + Clone)
+        -> Self::Target;
```
Comment (Twey) [inline linera-views/src/views/mod.rs:106]: `impl FnOnce + Clone` should generally be `impl Fn`.

File: linera-views/src/views/mod.rs (hunk 7 above)
Comment (bart-linera) [reply linera-views/src/views/mod.rs:100]: Without it, we'd have to do separate impls for, say, `ExecutionStateView<ViewContext>` and `ExecutionStateView<InactiveContext>`. Also, it makes sense for a single type to have the ability to have its context replaced by many different context types, not just a single one.

File: linera-views/src/views/mod.rs (hunk 8 above)
Comment (bart-linera) [reply linera-views/src/views/mod.rs:106]: That wouldn't work with multiple calls of `self.subfield.with_context(ctx)` within an implementation of `SomeView::with_context`. It would result in a "value used after move". `Fn` doesn't imply `Clone`, and we need the `Clone`.
