### PR TITLE
Fix dangling endpoint to chain worker actor that failed to start

### LINKED ISSUE #3295: Invalid chain worker endpoint can end up in the cache
# Description

When a request for a chain worker that's not already running is made, the following steps are made:

1. Create a channel to communicate with the actor
2. Add the sender endpoint to the chain worker cache
3. Start the actor with the receiver endpoint

However, if step 3 fails, the actor doesn't run and the receiver is immediately dropped. This means that any subsequent queries to the same chain will get the sender endpoint and fail to send a message.

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

Testnet is currently experiencing some panics when an attempt is made to send a request to a chain worker actor. The panic message says that the endpoint is closed. One possible cause is #3295, where a storage error could cause an endpoint to be added to the chain worker cache but its respective actor task wouldn't start.

## Proposal

Refactor the `ChainWorkerActor` so that it has a `run` method that loads the chain state from storage and then handles the incoming requests. If loading the state fails, then the error is reported to the next requester, and loading will be reattempted while the actor is running and receiving requests.

## Test Plan

CI should catch any regressions caused by this refactor.

#3299 tracks having a regression test for the issue.

## Release Plan

- These changes should be backported to the latest `devnet` branch, then
    - be released in a validator hotfix.
- These changes should be backported to the latest `testnet` branch, then
    - be released in a validator hotfix.

This needs to be hotfixed because it may fix a bug that's in production.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)
- Closes #3295

### CODE REVIEW

File: linera-core/src/chain_worker/actor.rs [hunk 1]
```diff
@@ -176,8 +176,45 @@ impl<StorageClient> ChainWorkerActor<StorageClient>
...
+                delivery_notifier.clone(),
+                chain_id,
+            )
+            .await;
+
+            match load_result {
+                Ok(actor) => break actor,
+                Err(error) => match incoming_requests.recv().await {
+                    Some(request) => request.send_error(error),
+                    None => return,
```
Comment (afck) [inline linera-core/src/chain_worker/actor.rs:208]: Should we log the error here?

**Review by afck — APPROVED** [review]

File: linera-core/src/chain_worker/actor.rs [hunk 2]
```diff
@@ -176,8 +176,45 @@ impl<StorageClient> ChainWorkerActor<StorageClient>
...
+                tracked_chains.clone(),
+                delivery_notifier.clone(),
+                chain_id,
+            )
+            .await;
+
+            match load_result {
+                Ok(actor) => break actor,
+                Err(error) => match incoming_requests.recv().await {
+                    Some(request) => request.send_error(error),
```
Comment (deuszx) [inline linera-core/src/chain_worker/actor.rs:207]: What happens to failed requests?

File: linera-core/src/chain_worker/actor.rs (hunk 1 above)
Comment (jvff) [reply linera-core/src/chain_worker/actor.rs:209]: Yes indeed! Thanks for catching this. I added a `warn!` above, to log the error as soon as it is received, otherwise we would only log when the error is sent to a request, which would lose timing information.

File: linera-core/src/chain_worker/actor.rs (hunk 2 above)
Comment (jvff) [reply linera-core/src/chain_worker/actor.rs:208]: I believe it depends on the request, but most of them abort the operation :thinking:

Comment (deuszx) [reply linera-core/src/chain_worker/actor.rs:208]: The current code will try to load a chain worker for every incoming request and fail them - one-by-one. I wonder whether the alternatives:
- failing all of them at once
- blocking until loaded
- panic(?)

were considered? Not being able to load a chain worker is a fatal error, right? It practically stalls the chain.

Comment (jvff) [reply linera-core/src/chain_worker/actor.rs:208]: I didn't give those alternatives much thought because I figured that a storage error could be temporary (e.g., network issue to the database). The option to block until the chain state is loaded is tricky, because of the mixture between `async` code (to load it) and synchronous code (the endpoint cache).
