### PR TITLE
Address the hash invalidation problem in QueueView

### LINKED ISSUE #1692: `QueueView`'s `HashableView` implementation suffers from a hash collision
Reproduction steps:

- Check out `e624f9fdf28a7bfcd38bef316d30399ce87400ac`
- Apply the following patch to make `queue_view_mutability_check` deterministic:
<details><summary>Test determinism patch</summary>
<p>

```diff
diff --git a/linera-views/Cargo.toml b/linera-views/Cargo.toml
index 70a9d045f8..a714a6c17e 100644
--- a/linera-views/Cargo.toml
+++ b/linera-views/Cargo.toml
@@ -53,7 +53,7 @@ tokio = { workspace = true, features = ["rt", "sync"] }
 anyhow = { workspace = true, optional = true }
 tracing.workspace = true
 http.workspace = true
-rand.workspace = true
+rand = { workspace = true, features = ["small_rng"] }
 scylla = { workspace = true, optional = true }
 rocksdb = { workspace = true, optional = true }
 aws-config = { workspace = true, optional = true }
diff --git a/linera-views/tests/queueview_tests.rs b/linera-views/tests/queueview_tests.rs
index c908d4f7a9..2fdb3ae837 100644
--- a/linera-views/tests/queueview_tests.rs
+++ b/linera-views/tests/queueview_tests.rs
@@ -16,7 +16,7 @@ pub struct StateView<C> {
 #[tokio::test]
 async fn queue_view_mutability_check() {
     let context = create_memory_context();
-    let mut rng = rand::rngs::StdRng::seed_from_u64(2);
+    let mut rng = rand::rngs::SmallRng::seed_from_u64(6148914691236517205);
     let mut vector = Vec::new();
     let n = 20;
     for _ in 0..n {
```

</p>
</details> 

- Run the test: `cargo test -p linera-views -- queue_view_mutability_check`
- Observe the test failure.

The test appears to fail due to a hash collision between the two following `QueueView`s:

```
[linera-views/tests/queueview_tests.rs:85] (&elements, &new_elements) = (
    [
        187,
        223,
        57,
        242,
        205,
        131, // this is 28 in new_elements
        14,
        124,
        24,
        24,
        8,
        34,
        108,
        32,
        228,
        106,
        13,
        118,
        80,
        99,
        244,
        73,
        73,
        31,
    ],
    [
        187,
        223,
        57,
        242,
        205,
        28, // this is 131 in elements
        14,
        124,
        24,
        24,
        8,
        34,
        108,
        32,
        228,
        106,
        13,
        118,
        80,
        99,
        244,
        73,
        73,
        31,
    ],
)

thread 'queue_view_mutability_check' panicked at linera-views/tests/queueview_tests.rs:87:17:
assertion `left != right` failed
  left: 738777121bd78217
 right: 738777121bd78217
```

### PR DESCRIPTION
**Pull request by MathieuDutSik**
## Motivation

The issue was identified in issue #1692 and is now addressed.

## Proposal

It was simply a hash invalidation that was missing. Otherwise the test was reenabled and restructured a little bit.

## Test Plan

The CI should do it.

## Release Plan

Not relevant.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)
- Fixes #1692

### CODE REVIEW

File: linera-views/tests/queueview_tests.rs [hunk 1]
```diff
@@ -43,15 +41,13 @@ async fn queue_view_mutability_check() {
...
+            if choice == 1 && count > 0 {
                 // deleting some entries
-                if count > 0 {
-                    let n_remove = rng.gen_range(0..count);
-                    for _ in 0..n_remove {
-                        view.queue.delete_front();
-                        // slow but we do not care for tests.
-                        new_vector.remove(0);
-                    }
+                let n_remove = rng.gen_range(0..count);
```
Comment (afck) [inline linera-views/tests/queueview_tests.rs:46]: Should this be `0..=count` or do we want to avoid removing all of them?

**Review by afck — APPROVED** [review]

File: linera-views/tests/queueview_tests.rs (hunk 1 above)
Comment (MathieuDutSik) [reply linera-views/tests/queueview_tests.rs:46]: Yes, you are right. Thank you.
