### PR TITLE
Fix "skipped proposal" scenario; take note of proposals even if they fail.

### LINKED ISSUE #2971: Take note of block proposals in the client without handling them.
[The client currently asks validators for pending block proposals and then handles them locally.](https://github.com/linera-io/linera-protocol/blob/3d05b4de633efef92f6a3e21e381257d9555951d/linera-core/src/client/mod.rs#L1715) This serves two purposes:
* If the proposal is in `Round::Fast`, it counts as locked, so the client _must_ re-propose that same block in a later round.
* If it is in `Round::MultiLeader(r)` and the client wants to propose a block, it _should_ not do that in the same round, but it can make a proposal in round `r + 1` without waiting for a timeout.

In the first case, the block cannot use any oracles.
In the second case, however, the block could be using oracles and therefore handling it locally could fail. On the other hand, we don't really care about the block itself there: We only need to know _that_ a proposal was made, not _which_ one.

Let's add a way for the client to keep track of proposals in the current round without executing them (but still checking the proposer's signature), so that the protocol works as intended in the second case even for blocks using oracles.

## Alternative: Use Timeouts?

We could also just rely on timeouts instead, and by default configure all multi-leader rounds to have timeout 0. That requires one more round-trip in the second case, but simplifies the protocol and brings the multi leader mode in line with the single leader one.

### PR DESCRIPTION
**Pull request by afck**
## Motivation

Proposals by other chain owners that the client learns about from validators can fail to execute locally, e.g. due to different oracle values. But in multi-leader rounds, clients need to take not of such failed proposals anyway, so they know that they shouldn't also make a conflicting proposal in the same round.

## Proposal

Add another `signed_proposed_block` field to the chain manager to keep track of this.

## Test Plan

A regression test was added; and it failed without this fix.

## Release Plan

- Nothing to do / These changes follow the usual release cycle.

## Links

- Closes #2971.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

### CODE REVIEW

File: linera-chain/src/manager.rs [hunk 1]
```diff
@@ -154,6 +154,12 @@ where
     /// The probability distribution for choosing a fallback round leader.
     #[cfg_attr(with_graphql, graphql(skip))] // Derived from validator weights.
     pub fallback_distribution: RegisterView<C, Option<WeightedAliasIndex<u64>>>,
+    /// Highest-round authenticated block that we have received, but not necessarily check yet.
```
Comment (bart-linera) [inline linera-chain/src/manager.rs]:
```suggestion
    /// Highest-round authenticated block that we have received, but not necessarily checked yet.
```

**Review by bart-linera — APPROVED** [review]
